site_name: eZ Platform User Documentation
repo_url: https://github.com/ezsystems/user-documentation
copyright: "Copyright 1999-2019 eZ Systems AS and others"
pages:
    - 'Documentation': 'index.md'
    - 'Getting started': 'getting_started.md'
    - 'Content model': 'content_model.md'
    - 'Creating content — basic': 'creating_content_basic.md'
    - 'Organizing the content': 'organizing_the_content.md'
    - 'Publishing': 'publishing.md'
    - 'Creating content — advanced': 'creating_content_advanced.md'
    - 'Organizing the site': 'organizing_the_site.md'
    - 'FAQ': 'faq.md'
theme:
  name: null
  custom_dir: 'material'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'

  font: false
  logo: 'images/eZ-Brandmark.png'
  feature:
    tabs: false
  search_index_only: false

theme_dir: material

extra:
  version_warning:
    latest: ['2.5']
    previous_lts: ['1.7', '1.13']
    lts: ['2.5']
    ft: ['2.2', '2.3', '2.4']
    dev: ['master']
  append_bootstrap: []

  related_docs:
    - title: 'eZ Platform User Documentation'
      url: '/projects/userguide'
    - title: 'eZ Platform Developer Documentation'
      url: '/'
    - title: 'eZ Services Documentation'
      url: '/projects/ezservices'

extra_css:
  - fonts/MavenPro.css
  - css/custom.css
  - css/docs.switcher.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/custom.js
  - js/docs.switcher.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
