site_name: User Documentation
repo_url: https://github.com/ezsystems/user-documentation
site_url: https://doc.ibexa.co/projects/userguide/en/latest/
copyright: "Copyright 1999-2021 Ibexa AS and others"
nav:
    - 'eZ Platform User Documentation': 'index.md'
    - 'Getting started': 'getting_started.md'
    - 'Content model': 'content_model.md'
    - 'Creating content — basic': 'creating_content_basic.md'
    - 'Organizing the content': 'organizing_the_content.md'
    - 'Publishing': 'publishing.md'
    - 'Creating content — advanced': 'creating_content_advanced.md'
    - 'Organizing the site': 'organizing_the_site.md'

theme:
    name: material
    custom_dir: 'theme'
    favicon: 'images/favicon.png'
    language: 'en'
    palette:
        primary: 'blue grey'
        accent: 'deep orange'
    logo: 'images/ibexa-dxp-logo.svg'

plugins:
    - search
    - macros:
        j2_block_start_string: '[[%'
        j2_block_end_string: '%]]'
        j2_variable_start_string: '[[='
        j2_variable_end_string: '=]]'

extra:
  version_warning:
    latest: ['3.3']
    previous_lts: ['2.5', '1.13']
    lts: ['3.3']
    ft: ['3.2','3.1']
    dev: ['master']
  append_bootstrap:
    - '/index.md'

  related_docs:
    - title: 'User Documentation'
      url: '/projects/userguide'
    - title: 'Developer Documentation'
      url: '/'

extra_css:
  - fonts/MavenPro.css
  - css/codehilite.css
  - css/switcher.css
  - css/custom.css
  - css/page-not-found.css
  - css/navigation.css
  - css/docs.switcher.css
  - css/jquery-ui.min.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/jquery-ui.min.js
  - js/custom.js
  - js/docs.switcher.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
