site_name: eZ Platform User Documentation
repo_url: https://github.com/ezsystems/user-documentation
copyright: "Copyright 1999-2020 Ibexa and others"
nav:
    - 'eZ Platform User Documentation': 'index.md'
    - 'Getting started': 'getting_started.md'
    - 'Content model': 'content_model.md'
    - 'Creating content – basic': 'creating_content_basic.md'
    - 'Working with Page': 'working_with_page.md'
    - 'Organizing the content': 'organizing_the_content.md'
    - 'Multi-file content management': 'multi_file_content_management.md'
    - 'Publishing':
        - Publishing Content: 'publishing/publishing.md'
        - Editorial workflow: 'publishing/editorial_workflow.md'
        - Flex workflow: 'publishing/flex_workflow.md'
        - Advanced publishing options: 'publishing/advanced_publishing_options.md'
    - 'Creating content – advanced': 'creating_content_advanced.md'
    - 'Organizing the site': 'organizing_the_site.md'
    - 'Searching': 'search.md'
    - Personalization:
        - 'Personalization': 'personalization/personalization.md'
        - 'Use cases': 'personalization/use_cases.md'
        - 'Dashboard': 'personalization/dashboard.md'
        - 'Event Types': 'personalization/event_types.md'
        - 'Content Types': 'personalization/content_types.md'
        - 'Recommendation models': 'personalization/recommendation_models.md'
        - 'Filters': 'personalization/filters.md'
        - 'Scenarios': 'personalization/scenarios.md'
        - 'Content import': 'personalization/content_import.md'
        - 'User data import': 'personalization/user_data_import.md'
    - 'FAQ': 'faq.md'
theme:
  name: null
  custom_dir: 'material'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'

  font: false
  logo: 'images/eZ-Brandmark.png'
  feature:
    tabs: false
  search_index_only: false

# theme_dir: material

plugins:
    - search
    - macros:
        j2_block_start_string: '[[%'
        j2_block_end_string: '%]]'
        j2_variable_start_string: '[[='
        j2_variable_end_string: '=]]'

extra:
  version_warning:
    latest: ['3.2']
    previous_lts: ['1.13']
    lts: ['2.5']
    ft: ['3.0','3.1']
    dev: ['master']
  append_bootstrap: []

  related_docs:
    - title: 'eZ Platform User Documentation'
      url: '/projects/userguide'
    - title: 'eZ Platform Developer Documentation'
      url: '/'
    - title: 'eZ Commerce'
      url: '/projects/ezcommerce'

extra_css:
  - fonts/MavenPro.css
  - css/custom.css
  - css/docs.switcher.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/custom.js
  - js/docs.switcher.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
