site_name: Ibexa User Documentation
repo_url: https://github.com/ezsystems/user-documentation
copyright: "Copyright 1999-2020 Ibexa and others"
nav:
    - 'Ibexa User Documentation': 'index.md'
    - 'Getting started': 'getting_started.md'
    - 'Content model': 'content_model.md'
    - 'Creating content':
        - 'Creating content – basic': 'creating_content_basic.md'
        - 'Creating content – advanced': 'creating_content_advanced.md'
        - 'Editing images': 'editing_images.md'
    - 'Publishing':
        - Publishing Content: 'publishing/publishing.md'
        - Editorial workflow: 'publishing/editorial_workflow.md'
        - Advanced publishing options: 'publishing/advanced_publishing_options.md'
    - 'Organizing':
        - 'Organizing the site': 'site_organization/organizing_the_site.md'
        - 'Site Factory': 'site_organization/site_factory.md'
        - 'Organizing the content': 'site_organization/organizing_the_content.md'
        - 'Multi-file content management': 'site_organization/multi_file_content_management.md'
        - 'Working with Page': 'site_organization/working_with_page.md'
    - 'Searching': 'search.md'
    - Shop administration:
        - 'Shop administration': 'shop_administration/shop_administration.md'
        - 'Cockpit': 'shop_administration/cockpit.md'
        - 'Components': 'shop_administration/components.md'
        - 'Configuration settings': 'shop_administration/configuration_settings.md'
        - 'Manage orders': 'shop_administration/manage_orders.md'
        - 'Manage prices and stock': 'shop_administration/manage_prices_and_stock.md'
        - 'Manage products and categories': 'shop_administration/manage_products_and_categories_with_the_ez_dataprovider.md'
        - 'Manage users': 'shop_administration/manage_users.md'
        - 'Permissions': 'shop_administration/permissions.md'
        - 'Translations': 'shop_administration/translations.md'
    - Managing shop content:
        - 'Embed product': 'managing_shop_content/embed_product.md'
        - 'Pages in the shop': 'managing_shop_content/landingpages.md'
        - 'Navigation structure': 'managing_shop_content/navigation_structure.md'
        - 'Legal documents': 'managing_shop_content/legal_documents.md'
    - Personalization:
        - 'Personalization': 'personalization/personalization.md'
        - 'Use cases': 'personalization/use_cases.md'
        - 'Dashboard': 'personalization/dashboard.md'
        - 'Event Types': 'personalization/event_types.md'
        - 'Content Types': 'personalization/content_types.md'
        - 'Recommendation models': 'personalization/recommendation_models.md'
        - 'Filters': 'personalization/filters.md'
        - 'Scenarios': 'personalization/scenarios.md'
        - 'Content import': 'personalization/content_import.md'
        - 'User data import': 'personalization/user_data_import.md'
theme:
  name: null
  custom_dir: 'material'
  favicon: 'img/favicon.ico'
  language: 'en'
  palette:
    primary: 'blue grey'
    accent: 'deep orange'

  font: false
  feature:
    tabs: false
  search_index_only: false

# theme_dir: material

plugins:
    - search
    - macros:
        j2_block_start_string: '[[%'
        j2_block_end_string: '%]]'
        j2_variable_start_string: '[[='
        j2_variable_end_string: '=]]'

extra:
  version_warning:
    latest: ['3.3']
    previous_lts: ['2.5', '1.13']
    lts: ['3.3']
    ft: ['3.2','3.1']
    dev: ['master']
  append_bootstrap:
    - '/index.md'

  related_docs:
    - title: 'Ibexa User Documentation'
      url: '/projects/userguide'
    - title: 'Ibexa Developer Documentation'
      url: '/'
  # Global variables
  product_name: 'Ibexa DXP'
  product_name_content: 'Ibexa Content'
  product_name_exp: 'Ibexa Experience'
  product_name_com: 'Ibexa Commerce'

extra_css:
  - fonts/MavenPro.css
  - css/custom.css
  - css/docs.switcher.css
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css'

extra_javascript:
  - js/jquery.min.js
  - js/custom.js
  - js/docs.switcher.js
  - '//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      guess_lang: false
      linenums: true
      css_class: codehilite
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.details
